# Generated by Django 4.0.4 on 2022-05-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpagetag_blogtagindexpage_blogpage_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
    ]
