# Generated by Django 4.0.4 on 2022-05-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogauthor_blogpage_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name_plural': 'blog users'},
        ),
    ]
