# Generated by Django 4.0.4 on 2022-05-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogauthor_avatar_blogauthorsorderable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='author',
            new_name='authors',
        ),
    ]
